<a href="https://colab.research.google.com/github/MuhammadHassan667410/160-Days-of-learning-complete-AI/blob/main/Phase%202%20%3A%20Machine%20Learning%2C(Day%2020%20to%2050)/Supervised%20ML(Day%2020%20to%2028)/KNN_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv('KNN_Large_Practice_Dataset.csv')

In [ ]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6       67             65             26       36  24.8   
1             14      116             65             32        0  39.2   
2             10       83             69             24       74  27.0   
3              7      124             77             21       80  28.5   
4              6      127             76             16      100  21.2   
..           ...      ...            ...            ...      ...   ...   
995            6      127            100             27       18  26.7   
996            7      117             84             19       70  24.0   
997            2      146             63              9      153  33.4   
998            1      108             62             14       81  39.7   
999           14       93             62             23       60  32.2   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.220   22        1  
1                      -0.060   39        1  
2                       0.959   34        0  
3                       0.813   28        1  
4                       0.591   58        1  
..                        ...  ...      ...  
995                     0.251   68        0  
996                     0.383   34        0  
997                     0.191   23        0  
998                     0.257   69        1  
999                    -0.043   73        1  

[1000 rows x 9 columns]

In [ ]:
removing_zeros = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
for column in removing_zeros:
    data[column] = data[column].replace(0, np.nan)
    mean = int(data[column].mean(skipna=True))
    data[column] = data[column].replace(np.nan, mean)

In [ ]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6       67             65           26.0     36.0  24.8   
1             14      116             65           32.0    116.0  39.2   
2             10       83             69           24.0     74.0  27.0   
3              7      124             77           21.0     80.0  28.5   
4              6      127             76           16.0    100.0  21.2   
..           ...      ...            ...            ...      ...   ...   
995            6      127            100           27.0     18.0  26.7   
996            7      117             84           19.0     70.0  24.0   
997            2      146             63            9.0    153.0  33.4   
998            1      108             62           14.0     81.0  39.7   
999           14       93             62           23.0     60.0  32.2   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.220   22        1  
1                      -0.060   39        1  
2                       0.959   34        0  
3                       0.813   28        1  
4                       0.591   58        1  
..                        ...  ...      ...  
995                     0.251   68        0  
996                     0.383   34        0  
997                     0.191   23        0  
998                     0.257   69        1  
999                    -0.043   73        1  

[1000 rows x 9 columns]

In [ ]:
y = data['Outcome']
x = data.drop(['Outcome'], axis=1)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [ ]:
x_scaled

array([[-0.33679307, -1.77370728, -0.42569824, ..., -1.221953  ,
        -0.95635159, -1.65822784],
       [ 1.24904834, -0.1609469 , -0.42569824, ...,  1.13324071,
        -1.91175801, -0.55555335],
       [ 0.45612764, -1.24709165, -0.09181727, ..., -0.86213174,
         1.56523893, -0.87986938],
       ...,
       [-1.12971377,  0.82645741, -0.59263873, ...,  0.18462102,
        -1.0553044 , -1.59336463],
       [-1.32794395, -0.42425472, -0.67610898, ...,  1.21501827,
        -0.83010146,  1.3903428 ],
       [ 1.24904834, -0.91795688, -0.67610898, ..., -0.01164512,
        -1.85375119,  1.64979562]], shape=(1000, 8))

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=50)

In [ ]:
import math
math.sqrt(len(y_test))

14.142135623730951

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=14, p=2, metric='euclidean')
KNN.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=14)

In [ ]:
y_pred = KNN.predict(x_test)

In [ ]:
y_pred

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1])

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
acc = accuracy_score(y_test, y_pred)
print(f'Accuracy: {acc: .2f}')

Accuracy:  0.56


In [ ]:
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.59      0.62      0.60       107
           1       0.53      0.51      0.52        93

    accuracy                           0.56       200
   macro avg       0.56      0.56      0.56       200
weighted avg       0.56      0.56      0.56       200



In [ ]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[66, 41],
       [46, 47]])

In [ ]:
import